### ISSUE TITLE
Transition properties aren't being prefixed correctly in mobile Safari

### ISSUE THREAD

**Issue by xymostech** [rofrischmann/inline-style-prefix-all#11]
See https://github.com/Khan/aphrodite/issues/68 for some more specifics on what's going on. Basically, it looks like this double prefixing, by generating `transition: -webkit-transform, transform; -webkit-transition: -webkit-transform, transform;` (i.e. the `-webkit-transform` value is being prefixed in both the prefixed `-webkit-transition` as well as the unprefixed `transition` property).

It seems like this should just be generating `transition: transform; -webkit-transition: -webkit-transform;`, since browsers are either going to use the prefixed version or not, and don't expect a mix of both.

**Comment by rofrischmann** [comment]
The problem is that you can't tell which prefixes the browser needs. Some need the transition prefixed and the value, some only the transition, but also some only the value as it depends on the value.

I will comment the issue at your repo, found something else thats strange.

**Comment by crm416** [comment]
I responded in Khan/aphrodite#68, but I believe this is still a valid issue.

Is there ever a case in which the `-${prefix}-transition` value would need to include vendor prefixed properties with prefixes other than `${prefix}`?  In other words: could the autoprefixer be changed to stop including `-moz-transform` and `-ms-transform` in the `-webkit-transition` value? And, similarly, `-moz-transform` and `-webkit-transform` in the `-ms-transition` value.

**Comment by rofrischmann** [comment]
Actually you're right. The `-webkit-transition` only needs unprefixed or prefixed properties, depending on the browser and its version (which is why we add both). Yet it does not get `moz` or `ms` values which makes me wonder how you get those at all.
The `ms-transition` on the other hand is still a valid issue I guess. We should not add prefixes to the value at all, because there is no `ms` prefixed transition and will never be. 

I will remove those prefixes later :P Thanks for reminding! @crm416
