### ISSUE TITLE
Prefixing value fallback arrays

### ISSUE THREAD

**Issue by rtsao** [rofrischmann/inline-style-prefix-all#13]
Many CSS-in-JS libraries support value fallbacks via arrays. It would be nice if these were prefixed.

For example:
```js
const input = {
  width: ['calc(100% - 50px)', 'min-content']
}

const output = {
  width: [
    '-webkit-calc(100% - 50px)',
    '-moz-calc(100% - 50px)',
    'calc(100% - 50px)',
    '-webkit-min-content',
    '-moz-min-content',
    'min-content'
}
```

I'd be happy to look into implementing this. Feel free to close this issue if you think this is out of scope.

**Comment by rofrischmann** [comment]
I think the use case is quite valid, but I am not sure if this adds to much complexity to the whole library. I'd love to see your implementation though. My goal is to keep the package as small as possible, so perhaps you would iterate those arrays once within the main function instead of checking inside each plugin.
