### ISSUE TITLE
`transition-property: transform` is not idempotent

### ISSUE THREAD

**Issue by ajoslin** [rofrischmann/inline-style-prefix-all#8]
Prefixing transition properties is not idempotent -- if you pass in the same object to prefix multiple times, it will break the style object each time.

```js
var assert = require('assert')
var prefix = require('inline-style-prefix-all')
var style = {
  transitionProperty: 'transform'
}

JSON.stringify(prefix(style)) // => yields correct output
JSON.stringify(prefix(style)) // => yields insane output
```

Example: http://requirebin.com/?gist=73acb9d22d0998fb299932282ae31358

**Comment by rofrischmann** [comment]
Oh I see. I think we need to check if the value already includes prefixed versions and if so not do anything. Thanks for reporting! I am currently having exams until May, 16. If you want to fix this on your own and push a pull request, feel free to! Otherwise this will take some time until it gets fixed.

**Comment by ajoslin** [comment]
:+1: Opened #9, let's discuss there.
